"""
simulator.py
================================================================================
Physics-structured dynamic simulator for a single naturally flowing oil well
with one production choke.

Honeywell Campus Connect - Autonomous Production Choke Controller

Model structure (steady state is solved from first principles, dynamics are
first-order lags identified from step-test data):

    1. Reservoir inflow (linear IPR)      Q  = PI * (Pr - BHP)
    2. Tubing lift performance (VLP)      WHP = BHP - dP_tubing(Q)
    3. Production choke (orifice eqn)     Q  = CdA(u) * sqrt(WHP - FLP)
    4. Gathering manifold back-pressure   FLP = f(u)      (empirical, calibrated)

The four equations are solved simultaneously for (Q, BHP, WHP) at every
steady state; the transient response is generated by applying an independent
first-order lag to each measured variable, with time constants identified from
the reference step-test data.

Assumptions (per challenge statement)
    * single naturally flowing well, single production choke
    * no gas lift / no ESP / no artificial lift
    * no facility network interaction (manifold treated as a calibrated
      back-pressure boundary condition)
    * constant reservoir properties, constant GOR and water cut
    * choke opening u [%] is the only manipulated variable
    * control interval Ts = 1 hour
================================================================================
"""

from __future__ import annotations

import json
import os
import warnings
from dataclasses import dataclass, field, replace

import numpy as np
from scipy.optimize import brentq

# ------------------------------------------------------------------------------
# Physical / calibrated parameters
# ------------------------------------------------------------------------------


@dataclass
class WellParameters:
    """Physical parameters of the well, calibrated against the reference dataset."""

    # --- Reservoir inflow performance (IPR) -----------------------------------
    Pr: float = 3568.8          # average reservoir pressure                [psi]
    PI: float = 0.2313          # productivity index              [bbl/hr per psi]

    # --- Tubing lift performance (VLP): dP_tub = t0 + t1*Q + t2*Q^2 ----------
    # In this rate window the gas-lightening of the column dominates wall
    # friction, so the tubing pressure loss falls as rate increases.
    t0: float = 3297.5
    t1: float = -4.8470
    t2: float = 0.0055350

    # --- Production choke characteristic: CdA(u) = c0 + c1*u + c2*u^2 --------
    # Effective discharge coefficient x flow area, [bbl/hr / sqrt(psi)]
    c0: float = 3.7870
    c1: float = 0.184000
    c2: float = 0.00105630

    # --- Gathering-manifold back-pressure: FLP = m0 + m1*u + m2*u^2 ----------
    m0: float = 212.513
    m1: float = -0.69230
    m2: float = -0.0029900

    # --- Dynamics: first-order time constants identified from step tests -----
    tau_Q: float = 5.89         # oil rate settling time constant             [h]
    tau_WHP: float = 9.82       # wellhead pressure time constant             [h]
    tau_FLP: float = 6.79       # flowline pressure time constant             [h]
    tau_BHP: float = 13.53      # bottom-hole pressure time constant          [h]
    tau_WHT: float = 20.0       # wellhead temperature - thermal, so slowest   [h]
    theta_FLP: float = 0.24     # small transport delay on FLP                [h]

    # --- Actuator ------------------------------------------------------------
    u_min: float = 0.0          # choke fully closed                          [%]
    u_max: float = 100.0        # choke fully open                            [%]
    du_max: float = 5.0         # ramp-rate limit per control interval        [%]

    # --- Informational variables (monitored, NOT active constraints) ---------
    # The brief names WHT and annulus pressure as variables that "should be
    # recognised as part of a complete production operating envelope".
    T_res: float = 200.0        # reservoir / bottom-hole temperature         [F]
    T_amb: float = 80.0         # ambient temperature at surface              [F]
    wht_a: float = 69.3         # heat-loss group; higher rate -> hotter wellhead
    AP_ref: float = 250.0       # annulus pressure at the reference WHT      [psi]
    WHT_ref: float = 140.0      # reference wellhead temperature              [F]
    AP_dPdT: float = 3.5        # annular thermal pressure buildup      [psi / F]

    # --- Reservoir / fluid disturbances (all OFF by default; the challenge
    #     assumes constant reservoir properties. These exist so we can TEST
    #     what happens when that assumption is violated.)
    Pr_decline: float = 0.0     # reservoir pressure decline rate       [psi/h]
    water_cut: float = 0.0      # fraction of liquid that is water         [-]

    # --- Measurement noise (1 sigma), representative of field instrumentation
    noise_Q: float = 0.60       # [bbl/hr]
    noise_WHP: float = 0.50     # [psi]
    noise_FLP: float = 0.45     # [psi]
    noise_BHP: float = 2.50     # [psi]


# Location of the editable limits file. The official safe operating ranges were
# NOT published with the problem statement; every numeric limit lives in this one
# file so the official values can be dropped in without touching any code.
LIMITS_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "config", "operating_limits.json")


@dataclass
class OperatingEnvelope:
    """
    Safe operating envelope - the hard constraints the controller must respect.

    Defaults mirror ``config/operating_limits.json``. Prefer
    :meth:`OperatingEnvelope.load` so that editing that file is enough to adopt
    a different (or the official) set of limits.
    """

    WHP_min: float = 200.0      # slugging / flowline entry limit            [psi]
    WHP_max: float = 320.0      # wellhead equipment rating                  [psi]
    FLP_min: float = 140.0      # minimum transport pressure to separator    [psi]
    FLP_max: float = 210.0      # gathering system rating                    [psi]
    BHP_min: float = 2850.0     # max drawdown: sand / bubble-point limit    [psi]
    BHP_max: float = 3300.0     # minimum drawdown for stable inflow         [psi]

    source: str = "built-in defaults"

    # -- loading / saving ----------------------------------------------------

    @classmethod
    def load(cls, path: str | None = None, quiet: bool = True) -> "OperatingEnvelope":
        """
        Build an envelope from ``config/operating_limits.json``.

        Falls back to the built-in defaults (with a warning) if the file is
        missing or malformed, so nothing ever fails silently on a bad edit.
        """
        path = path or LIMITS_FILE
        try:
            with open(path) as f:
                cfg = json.load(f)
            lim = cfg["limits"]
            env = cls(**{k: float(v["value"]) for k, v in lim.items()},
                      source=os.path.basename(path))
        except (OSError, KeyError, TypeError, ValueError) as exc:
            warnings.warn(f"could not read limits from {path} ({exc}); "
                          f"using built-in defaults", RuntimeWarning)
            return cls()
        env.validate()
        if not quiet:
            print(env.describe())
        return env

    def validate(self) -> None:
        """Reject an envelope that is empty or inverted."""
        for tag in ("WHP", "FLP", "BHP"):
            lo, hi = getattr(self, f"{tag}_min"), getattr(self, f"{tag}_max")
            if not hi > lo:
                raise ValueError(f"{tag} limits are inverted or empty: [{lo}, {hi}]")

    def describe(self) -> str:
        """Human-readable summary of the envelope and where it was loaded from."""
        return ("Operating envelope (source: %s)\n" % self.source
                + "\n".join(f"    {t:3s}  {getattr(self, t+'_min'):8.1f} – "
                             f"{getattr(self, t+'_max'):8.1f} psi"
                             for t in ("WHP", "FLP", "BHP")))

    def violations(self, WHP: float, FLP: float, BHP: float) -> list[str]:
        """Return a list of constraint names violated by this operating point."""
        v = []
        if WHP < self.WHP_min:
            v.append("WHP_min")
        if WHP > self.WHP_max:
            v.append("WHP_max")
        if FLP < self.FLP_min:
            v.append("FLP_min")
        if FLP > self.FLP_max:
            v.append("FLP_max")
        if BHP < self.BHP_min:
            v.append("BHP_min")
        if BHP > self.BHP_max:
            v.append("BHP_max")
        return v

    def is_feasible(self, WHP: float, FLP: float, BHP: float) -> bool:
        """True when this operating point is inside every limit."""
        return not self.violations(WHP, FLP, BHP)


# ------------------------------------------------------------------------------
# Steady-state solver
# ------------------------------------------------------------------------------


def choke_CdA(u: float, p: WellParameters) -> float:
    """Effective choke discharge coefficient x area as a function of opening."""
    u = float(np.clip(u, p.u_min, p.u_max))
    return max(p.c0 + p.c1 * u + p.c2 * u**2, 1e-3)


def flowline_pressure(u: float, p: WellParameters) -> float:
    """Gathering-manifold back-pressure downstream of the choke."""
    u = float(np.clip(u, p.u_min, p.u_max))
    return p.m0 + p.m1 * u + p.m2 * u**2


def tubing_dp(Q: float, p: WellParameters) -> float:
    """Total tubing pressure loss (hydrostatic + friction) at rate Q."""
    return p.t0 + p.t1 * Q + p.t2 * Q**2


def wellhead_temperature(Q: float, p: WellParameters | None = None) -> float:
    """
    Wellhead temperature from a Ramey-type heat-loss argument.

    Produced fluid leaves the reservoir at ``T_res`` and loses heat to the
    formation on the way up. The faster it flows, the less time it spends in the
    tubing, so the HOTTER it arrives at surface:

        WHT = T_amb + (T_res - T_amb) * exp(-a / Q)

    As Q -> 0 the fluid equilibrates with the surroundings; as Q -> inf it
    arrives at reservoir temperature.
    """
    p = p or WellParameters()
    Q = max(float(Q), 1e-3)
    return p.T_amb + (p.T_res - p.T_amb) * float(np.exp(-p.wht_a / Q))


def annulus_pressure(WHT: float, p: WellParameters | None = None) -> float:
    """
    Annulus pressure from annular thermal expansion (APB).

    In a packer-completed well the A-annulus is sealed, so its pressure is
    driven mainly by the temperature of the fluid it contains rather than by the
    production pressures. Heating the tubing heats the trapped annular fluid,
    which cannot expand, so the pressure rises.

    This is why annulus pressure is a WELL-INTEGRITY variable rather than a
    production one - and why it moves in the OPPOSITE direction to WHP, FLP and
    BHP as the choke opens.
    """
    p = p or WellParameters()
    return p.AP_ref + p.AP_dPdT * (float(WHT) - p.WHT_ref)


def steady_state(u: float, p: WellParameters | None = None) -> dict:
    """
    Solve the coupled IPR / VLP / choke system for the steady state at choke
    opening ``u``.

    Returns dict with keys Q, WHP, FLP, BHP.
    """
    p = p or WellParameters()
    FLP = flowline_pressure(u, p)
    CdA = choke_CdA(u, p)

    def residual(Q: float) -> float:
        """Choke-equation mismatch at rate ``Q``; zero at the solution."""
        BHP = p.Pr - Q / p.PI
        WHP = BHP - tubing_dp(Q, p)
        dP = WHP - FLP
        if dP <= 0.0:
            # Choke would be starved: return a large positive residual so the
            # root finder is pushed back towards lower rate.
            return Q + abs(dP)
        return Q - CdA * np.sqrt(dP)

    # Bracket the physical root. Residual is monotonically increasing in Q over
    # the well's stable operating branch.
    lo, hi = 1.0, 400.0
    f_lo, f_hi = residual(lo), residual(hi)
    if f_lo * f_hi > 0:
        # Expand / fall back to a coarse scan if the default bracket fails.
        grid = np.linspace(1.0, 500.0, 2000)
        vals = np.array([residual(q) for q in grid])
        sign_change = np.where(np.sign(vals[:-1]) != np.sign(vals[1:]))[0]
        if len(sign_change) == 0:
            Q = float(grid[np.argmin(np.abs(vals))])
            BHP = p.Pr - Q / p.PI
            WHT = wellhead_temperature(Q, p)
            return {"Q": Q, "WHP": BHP - tubing_dp(Q, p), "FLP": FLP, "BHP": BHP,
                    "WHT": WHT, "AP": annulus_pressure(WHT, p)}
        lo, hi = grid[sign_change[0]], grid[sign_change[0] + 1]

    Q = brentq(residual, lo, hi, xtol=1e-8)
    BHP = p.Pr - Q / p.PI
    WHP = BHP - tubing_dp(Q, p)
    WHT = wellhead_temperature(Q, p)
    return {"Q": float(Q), "WHP": float(WHP), "FLP": float(FLP), "BHP": float(BHP),
            "WHT": WHT, "AP": annulus_pressure(WHT, p)}


# ------------------------------------------------------------------------------
# Dynamic simulator
# ------------------------------------------------------------------------------


class WellSimulator:
    """
    Dynamic simulator of a single naturally flowing oil well.

    Interface required by the challenge::

        Q, WHP, FLP, BHP = simulator.step(choke_position)

    One call to :meth:`step` advances the plant by one control interval
    (Ts = 1 hour).
    """

    Ts: float = 1.0  # control interval [h]

    def __init__(
        self,
        u0: float = 30.0,
        params: WellParameters | None = None,
        noise: bool = True,
        seed: int | None = 42,
        enforce_ramp: bool = True,
        disturbances: list | None = None,
    ):
        # deep-copied so a time-varying reservoir pressure in one simulator
        # never leaks into another
        self.p = replace(params or WellParameters())
        self.disturbances = list(disturbances or [])
        self.noise = noise
        self.enforce_ramp = enforce_ramp
        self.rng = np.random.default_rng(seed)

        self.u = float(np.clip(u0, self.p.u_min, self.p.u_max))
        ss = steady_state(self.u, self.p)
        self.Q = ss["Q"] * (1.0 - self.p.water_cut)
        self.WHP, self.FLP, self.BHP = ss["WHP"], ss["FLP"], ss["BHP"]
        self.WHT, self.AP = ss["WHT"], ss["AP"]

        # First-order hold state for the small FLP transport delay
        self._flp_delay_buffer = [self.FLP]
        self.t = 0.0
        self.history: list[dict] = []
        self._log()

    # -- internals ------------------------------------------------------------

    def _lag(self, y: float, y_target: float, tau: float) -> float:
        """Advance one first-order lag by one sample (exact ZOH discretisation)."""
        a = np.exp(-self.Ts / tau)
        return a * y + (1.0 - a) * y_target

    def _apply_disturbances(self) -> None:
        """
        Advance any active reservoir / fluid disturbances by one interval.

        ``self.disturbances`` is a list of callables ``f(sim, t)`` applied every
        step, plus the continuous decline rate ``Pr_decline``.
        """
        if self.p.Pr_decline:
            self.p.Pr -= self.p.Pr_decline * self.Ts
        for fn in self.disturbances:
            fn(self, self.t)

    def _log(self) -> None:
        self.history.append(
            {
                "Time_hr": self.t,
                "Choke_pct": self.u,
                "OilRate_bbl_hr": self.Q,
                "WHP_psi": self.WHP,
                "FLP_psi": self.FLP,
                "BHP_psi": self.BHP,
                "WHT_F": self.WHT,
                "AP_psi": self.AP,
                "Pr_psi": self.p.Pr,
                "water_cut": self.p.water_cut,
            }
        )

    # -- public API -----------------------------------------------------------

    def step(self, choke_position: float) -> tuple[float, float, float, float]:
        """
        Apply ``choke_position`` [%] and advance the plant by one control
        interval.  Returns the measured ``(Q, WHP, FLP, BHP)``.
        """
        u_cmd = float(np.clip(choke_position, self.p.u_min, self.p.u_max))

        # Actuator ramp-rate limit is enforced by the plant as well as by the
        # controller, so an aggressive controller cannot cheat.
        if self.enforce_ramp:
            du = np.clip(u_cmd - self.u, -self.p.du_max, self.p.du_max)
            self.u = self.u + du
        else:
            self.u = u_cmd

        # ---- apply time-varying disturbances before solving the plant -----
        self._apply_disturbances()

        ss = steady_state(self.u, self.p)
        # produced OIL rate falls as water cut rises: the well lifts the same
        # total liquid, but a growing fraction of it is water
        ss["Q"] = ss["Q"] * (1.0 - self.p.water_cut)

        self.Q = self._lag(self.Q, ss["Q"], self.p.tau_Q)
        self.WHP = self._lag(self.WHP, ss["WHP"], self.p.tau_WHP)
        self.BHP = self._lag(self.BHP, ss["BHP"], self.p.tau_BHP)

        # FLP carries a small transport delay before its own lag
        self._flp_delay_buffer.append(ss["FLP"])
        n_delay = max(int(round(self.p.theta_FLP / self.Ts)), 0)
        flp_target = self._flp_delay_buffer[max(len(self._flp_delay_buffer) - 1 - n_delay, 0)]
        self.FLP = self._lag(self.FLP, flp_target, self.p.tau_FLP)

        # monitored variables: temperature lags the flow, and annulus pressure
        # follows temperature
        self.WHT = self._lag(self.WHT, ss["WHT"], self.p.tau_WHT)
        self.AP = annulus_pressure(self.WHT, self.p)

        self.t += self.Ts
        self._log()

        if self.noise:
            return (
                self.Q + self.rng.normal(0, self.p.noise_Q),
                self.WHP + self.rng.normal(0, self.p.noise_WHP),
                self.FLP + self.rng.normal(0, self.p.noise_FLP),
                self.BHP + self.rng.normal(0, self.p.noise_BHP),
            )
        return self.Q, self.WHP, self.FLP, self.BHP

    def measure(self) -> tuple[float, float, float, float]:
        """Current measurement without advancing time."""
        if self.noise:
            return (
                self.Q + self.rng.normal(0, self.p.noise_Q),
                self.WHP + self.rng.normal(0, self.p.noise_WHP),
                self.FLP + self.rng.normal(0, self.p.noise_FLP),
                self.BHP + self.rng.normal(0, self.p.noise_BHP),
            )
        return self.Q, self.WHP, self.FLP, self.BHP

    def dataframe(self) -> "pd.DataFrame":
        """Full logged history of the run as a DataFrame."""
        import pandas as pd

        return pd.DataFrame(self.history)


# ------------------------------------------------------------------------------
# Convenience: envelope analysis
# ------------------------------------------------------------------------------


_SS_TABLE_CACHE: dict = {}


def steady_state_table(u_grid=None, params: WellParameters | None = None):
    """
    Steady-state (Q, WHP, FLP, BHP) over a choke grid, cached.

    The plant's steady-state map is independent of the operating limits, so this
    is computed once and reused when scoring many candidate envelopes.
    """
    params = params or WellParameters()
    u_grid = np.arange(0.0, 100.05, 0.05) if u_grid is None else np.asarray(u_grid, float)
    key = (round(params.Pr, 6), round(params.PI, 8), round(params.water_cut, 6),
           len(u_grid), float(u_grid[0]), float(u_grid[-1]))
    hit = _SS_TABLE_CACHE.get(key)
    if hit is not None and len(hit["u"]) == len(u_grid):
        return hit
    rows = [steady_state(float(u), params) for u in u_grid]
    tbl = {"u": u_grid,
           "Q": np.array([r["Q"] for r in rows]) * (1.0 - params.water_cut),
           "WHP": np.array([r["WHP"] for r in rows]),
           "FLP": np.array([r["FLP"] for r in rows]),
           "BHP": np.array([r["BHP"] for r in rows]),
           "WHT": np.array([r["WHT"] for r in rows]),
           "AP": np.array([r["AP"] for r in rows])}
    _SS_TABLE_CACHE[key] = tbl
    return tbl


def envelope_scan(
    env: OperatingEnvelope | None = None,
    params: WellParameters | None = None,
    u_grid: np.ndarray | None = None,
):
    """
    Sweep the choke over its full range and report, for each opening, the
    steady-state operating point and which constraints (if any) are violated.
    """
    import pandas as pd

    env = env or OperatingEnvelope.load()
    params = params or WellParameters()
    u_grid = np.arange(0.0, 100.5, 0.5) if u_grid is None else u_grid

    rows = []
    for u in u_grid:
        ss = steady_state(float(u), params)
        v = env.violations(ss["WHP"], ss["FLP"], ss["BHP"])
        rows.append(
            {
                "Choke_pct": u,
                "Q": ss["Q"],
                "WHP": ss["WHP"],
                "FLP": ss["FLP"],
                "BHP": ss["BHP"],
                "WHT": ss["WHT"],
                "AP": ss["AP"],
                "feasible": len(v) == 0,
                "violations": ",".join(v),
            }
        )
    return pd.DataFrame(rows)


def max_safe_rate(env: OperatingEnvelope | None = None,
                  params: WellParameters | None = None,
                  strict: bool = True):
    """
    Maximum achievable oil rate that keeps every variable inside the envelope.

    Also reports which limit is binding at that point - useful because the
    binding constraint changes with the limit set, and a controller that only
    ever handles one of them is not really constrained control.

    ``strict=False`` returns ``None`` instead of raising when the envelope admits
    no feasible operating point (used when scoring randomised envelopes).
    """
    env = env or OperatingEnvelope.load()
    t = steady_state_table(params=params)
    feas = ((t["WHP"] >= env.WHP_min) & (t["WHP"] <= env.WHP_max)
            & (t["FLP"] >= env.FLP_min) & (t["FLP"] <= env.FLP_max)
            & (t["BHP"] >= env.BHP_min) & (t["BHP"] <= env.BHP_max))
    if not feas.any():
        if strict:
            raise RuntimeError("No feasible operating point exists for this envelope.")
        return None
    idx = np.where(feas)[0]
    j = idx[int(np.argmax(t["Q"][idx]))]

    # which limit is active at the maximum-rate point?
    margins = {"WHP_min": t["WHP"][j] - env.WHP_min, "WHP_max": env.WHP_max - t["WHP"][j],
               "FLP_min": t["FLP"][j] - env.FLP_min, "FLP_max": env.FLP_max - t["FLP"][j],
               "BHP_min": t["BHP"][j] - env.BHP_min, "BHP_max": env.BHP_max - t["BHP"][j]}
    # normalise by each variable's span so the comparison is dimensionless
    spans = {"WHP": env.WHP_max - env.WHP_min, "FLP": env.FLP_max - env.FLP_min,
             "BHP": env.BHP_max - env.BHP_min}
    binding = min(margins, key=lambda k: margins[k] / spans[k.split("_")[0]])

    return {
        "u": float(t["u"][j]), "Q": float(t["Q"][j]),
        "WHP": float(t["WHP"][j]), "FLP": float(t["FLP"][j]), "BHP": float(t["BHP"][j]),
        "binding": binding,
        "u_min_feasible": float(t["u"][idx].min()),
        "u_max_feasible": float(t["u"][idx].max()),
        "Q_min_feasible": float(t["Q"][idx].min()),
    }
